name: Build

on:
  push:
    branches: ["user.js"]
  # pull_request:
    # branches: [ "user.js" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Install pnpm with cache
      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run check

      - name: Commit
        continue-on-error: true
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: build"
